Repository komodorio/helm-charts, pull requests merged in 2023-12, with the labels that each got.

#276 CU-867985xym - Generate GitHub release from GH issue messages
  .buildkite/pipeline.yml
  .buildkite/pipeline_scripts/bump_version.sh
  .buildkite/pipeline_scripts/create_gh_pre_release.sh
  .gitignore
Labels: Sprints - Barzelim, Sprint 17 (19/11 - 2/12)

#278 CU-86798y3bd - set resources for metrics container
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 18 (3/12 - 16/12)

#274 Add node-enricher to komodor-agent chart
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/node-enricher/_containers.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 17 (19/11/23 - 2/12/23)

#279 CU-866b30503 - add api-key to node enricher container
  charts/komodor-agent/templates/node-enricher/_containers.tpl
Labels: Sprints - Troubleshooting, Sprint 18 (3/12/23 - 16/12/23)

#280 [skip ci] generate RN from PR titles instead of "public:" comments
  .buildkite/pipeline_scripts/create_gh_pre_release.sh
Labels: Sprints - Barzelim, Sprint 17 (19/11 - 2/12), Sprint 18 (3/12 - 16/12)

#261 feat(metrics): Improve metrics inventory performance and support large scale clusters
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/Makefile
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/metrics/_containers.tpl
  charts/komodor-agent/templates/metrics/_helpers.tpl
  charts/komodor-agent/templates/metrics/_volumes.tpl
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
  charts/komodor-agent/templates/metrics/configmap.yaml
  charts/komodor-agent/values.yaml
  scripts/telegraf/update-ecr.sh
Labels: Sprints - Troubleshooting, Sprint 18 (3/12/23 - 16/12/23)

#283 [skip ci] fix: Missing info in pre-release body
  .buildkite/pipeline_scripts/bump_version.sh
  .buildkite/pipeline_scripts/create_gh_pre_release.sh
Labels: Sprints - Barzelim, Sprint 18 (3/12 - 16/12)

#282 chore: make pre-release RC draft releases instead
  .buildkite/pipeline.yml
  .buildkite/pipeline_scripts/create_gh_draft_release.sh
Labels: Sprints - Barzelim, Sprint 19 (17/12 - 30/12)

#284 [skip ci] Unified komodor-agent image
  charts/k8s-watcher/Chart.yaml
  charts/k8s-watcher/templates/deployment.yaml
  charts/k8s-watcher/templates/metrics/init-container.yaml
  charts/k8s-watcher/values.yaml
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/metrics/_containers.tpl
  charts/komodor-agent/templates/node-enricher/_containers.tpl
  charts/komodor-agent/templates/watcher/_containers.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 19 (17/12 - 30/12)

#285 [skip ci] - fix(test): testing wrong agent version
  .buildkite/pipeline.yml
  .buildkite/tests/ci/use-new-agent-version.sh
Labels: Sprints - Barzelim, Sprint 19 (17/12 - 30/12)

#286 [skip ci] fix(vulnerability scan): Error when no vuln detected
  .buildkite/vulnerability-scan/exclude.yaml
  .buildkite/vulnerability-scan/main.py
Labels: Sprints - Barzelim, Sprint 19 (17/12 - 30/12)

#287 CU-86bwvf7rf - Fix daemon init container wrong startup command
  charts/k8s-watcher/templates/metrics/init-container.yaml
Labels: bug, Sprints - Barzelim, Sprint 19 (17/12 - 30/12)

#288 CU-86bwvpbtb - chore(komodor-agent) install node enricher by default
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 19 (17/12 - 30/12)
