Repository komodorio/helm-charts, pull requests merged in 2024-11, with the labels that each got.

#337 Security/updates nov 24
  .buildkite/pipeline_scripts/production-values.yaml
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/Makefile
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/deployment_metrics.yaml
  charts/komodor-agent/templates/metrics/_security.tpl
  charts/komodor-agent/templates/watcher/_containers.tpl
  charts/komodor-agent/templates/watcher/_security.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 42 (3/11 - 16/11)

#338 [CU-86c0x1d85] Add missing toleration on daemon
  charts/komodor-agent/Makefile
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 42 (3/11/24 - 17/11/24)

#339 feat: Mount installed values into watcher container
  charts/komodor-agent/templates/watcher/_volumes.tpl
Labels: Sprints - Barzelim, Sprint 42 (3/11 - 16/11)

#340 Chore: expand helm capabilities value
  .buildkite/tests/values_capabilities_test.py
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/_migrations.tpl
  charts/komodor-agent/templates/clusterrole.yaml
  charts/komodor-agent/templates/configmap.yaml
  charts/komodor-agent/templates/watcher/_containers.tpl
  charts/komodor-agent/values.yaml
Labels: Main Backlog

#341 feat: support custom update strategy
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/deployment_metrics.yaml
  charts/komodor-agent/values.yaml
Labels: Main Backlog

#342 Cu 86c13cj5w upgrade telegraf v.1.32.3
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 43 (17/11/24 - 1/12/24)

#343 Revert windows image
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 43 (17/11/24 - 1/12/24)
