Repository komodorio/helm-charts, pull requests merged in 2024-08, with the labels that each got.

#327 feat(komodor-agent): add telegraf deployment
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/Makefile
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/_custom_ca.tpl
  charts/komodor-agent/templates/_helpers.tpl
  charts/komodor-agent/templates/deployment_metrics.yaml
  charts/komodor-agent/templates/metrics/_containers_deamon.tpl
  charts/komodor-agent/templates/metrics/_containers_deployment.tpl
  charts/komodor-agent/templates/metrics/_helpers.tpl
  charts/komodor-agent/templates/metrics/_volumes.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 35 (28/7 - 11/8)

#328 Cu 86bzyyhjc update telegraf to 1.31.3
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 36 (11/8/24 - 25/8/24)

#329 Configurable redaction for secrets
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/configmap.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 36 (11/8 - 25/8)

#330 cu-86c0423hd Allow editing PriorityClass value in helm value
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/deployment_metrics.yaml
  charts/komodor-agent/templates/priorityclasses.yaml
  charts/komodor-agent/values.yaml
Labels: Main Backlog
