Repository komodorio/helm-charts, pull requests merged in 2024-03, with the labels that each got.

#306 [skip ci]- Extend pluto go vulnerability exclusion
  .buildkite/vulnerability-scan/exclude.yaml
Labels: Sprints - Barzelim, Sprint 24 (25/2 - 9/3)

#307 Cu 86bxmqkw8 win metrics
  charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/_helpers.tpl
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/metrics/_containers.tpl
  charts/komodor-agent/templates/metrics/_volumes.tpl
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 24 (25/2/24 - 9/3/24)

#308 [skip ci]- chore(mend): Exclude windows-telegraf image
  .buildkite/vulnerability-scan/main.py
Labels: Sprints - Barzelim, Sprint 25 (10/3 - 23/3)

#309 CU-86bxyw2gr - Update windows daemon tag and add tolerations in CI pipeline
  .buildkite/pipeline_scripts/production-values.yaml
  .buildkite/pipeline_scripts/update_agent.sh
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 25 (10/3/24 - 23/3/24)
