Repository komodorio/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#331 CU-86c081bq5 - Fix formatting of Tags when passed as helm values as string or as map
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/configmap.yaml
  charts/komodor-agent/templates/watcher/_containers.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 37 (25/8 - 7/9), Sprint 38 (8/9 - 21/9)

#332 chore: address opa violations
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/node-enricher/_containers.tpl
  charts/komodor-agent/templates/watcher/_containers.tpl
  charts/komodor-agent/values.yaml
Labels: Main Backlog

#334 CU-86c0fwhr0 - feat: allow not creating rbac at all
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/clusterrole.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 39 (22/9 - 5/10)

#333 add documentation for redaction.secret.keepOnlyHelmRelease
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 39 (22/9 - 5/10)
