Repository komodorio/helm-charts, pull requests merged in 2024-06, with the labels that each got.

#320 feat(komodor-agent): Support custom labels
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/_helpers.tpl
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/serviceaccount.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 31 (2/6 - 15/6)

#321 enable datadog profiling for our production agent
  .buildkite/pipeline_scripts/production-values.yaml
Labels: Sprints - Barzelim, Sprint 31 (2/6 - 15/6)

#322 CU-86bz7uwhh - deploy prod agent on on demand instances
  .buildkite/pipeline_scripts/production-values.yaml
Labels: Sprints - Barzelim, Sprint 32 (16/6 - 29/6)

#323 Cu 86bymm3dp support komodor owner refs
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 32 (16/6/24 - 30/6/24)

#325 Fix(komodor-agent): Wrong values
  .buildkite/tests/legacy_k8s_versions_test.py
  charts/komodor-agent/templates/watcher/_containers.tpl
  charts/komodor-agent/templates/watcher/_helpers.tpl
  charts/komodor-agent/templates/watcher/_volumes.tpl
Labels: Sprints - Barzelim, Sprint 32 (16/6 - 29/6)
