Repository komodorio/helm-charts, pull requests merged in 2024-04, with the labels that each got.

#311 Telegraf custom plugin windows
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/templates/metrics/_containers.tpl
  charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 26 (24/3/24 - 6/4/24)

#312 CU-86by8hnac - Add flag for RBAC permissions
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/clusterrole.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 27 (7/4 - 20/4)

#313 Cu 86by9b9xp support gather interval
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 27 (7/4/24 - 20/4/24)

#316 chore(k8s-watcher): Remove deprecated chart
  .buildkite/pipeline.yml
  .buildkite/pipeline_scripts/create_gh_draft_release.sh
  .buildkite/pipeline_scripts/legacy_bump_version.sh
  .buildkite/pipeline_scripts/legacy_test_helm_new_install.sh
  .buildkite/pipeline_scripts/legacy_test_helm_update_install.sh
  .buildkite/pipeline_scripts/legacy_update_agent.sh
  .buildkite/pipeline_scripts/publish_helm_charts.sh
  Makefile
  README.md
  charts/k8s-watcher/.helmignore
  charts/k8s-watcher/Chart.yaml
  charts/k8s-watcher/README.md
  charts/k8s-watcher/helm-fan-out.sh
  charts/k8s-watcher/kube-install/k8s-watcher/templates/clusterrole.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/configmap.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/daemonset.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/deployment.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/metrics/configmap-daemon.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/metrics/configmap.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/namespace.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/network-mapper/cluster-role.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/network-mapper/configmap.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/network-mapper/role.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/network-mapper/roles-binding.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/network-mapper/service.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/priorityclasses.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/resourcequota.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/secret-credentials.yaml
  charts/k8s-watcher/kube-install/k8s-watcher/templates/serviceaccount.yaml
  charts/k8s-watcher/templates/NOTES.txt
  charts/k8s-watcher/templates/_helpers.tpl
  charts/k8s-watcher/templates/_proxy_conf.tpl
  charts/k8s-watcher/templates/clusterrole.yaml
  charts/k8s-watcher/templates/configmap.yaml
  charts/k8s-watcher/templates/custom-ca/_helpers.tpl
  charts/k8s-watcher/templates/daemonset.yaml
  charts/k8s-watcher/templates/deployment.yaml
  charts/k8s-watcher/templates/metrics/configmap-daemon.yaml
  charts/k8s-watcher/templates/metrics/configmap.yaml
  charts/k8s-watcher/templates/metrics/daemonset.yaml
  charts/k8s-watcher/templates/metrics/deploy.yaml
  charts/k8s-watcher/templates/metrics/init-container.yaml
  charts/k8s-watcher/templates/namespace.yaml
  charts/k8s-watcher/templates/network-mapper/_helpers.tpl
  charts/k8s-watcher/templates/network-mapper/cluster-role.yaml
  charts/k8s-watcher/templates/network-mapper/configmap.yaml
  charts/k8s-watcher/templates/network-mapper/daemonset.yaml
  charts/k8s-watcher/templates/network-mapper/deployment.yaml
  charts/k8s-watcher/templates/network-mapper/role.yaml
  charts/k8s-watcher/templates/network-mapper/roles-binding.yaml
  charts/k8s-watcher/templates/network-mapper/service.yaml
  charts/k8s-watcher/templates/priorityclasses.yaml
  charts/k8s-watcher/templates/resourcequota.yaml
  charts/k8s-watcher/templates/secret-credentials.yaml
  charts/k8s-watcher/templates/serviceaccount.yaml
  charts/k8s-watcher/values.yaml
  docker-generate-kube.sh
Labels: Sprints - Barzelim, Sprint 28 (21/4 - 4/5)

#314 CU-86bygnv0j - chore: disable network mapper by default
  .buildkite/tests/values_capabilities_test.py
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 28 (21/4 - 4/5)
