Repository komodorio/helm-charts, pull requests merged in 2024-02, with the labels that each got.

#297 CU-3bfn5zu - allow edit and delete hpa
  charts/komodor-agent/templates/clusterrole.yaml
Labels: Operate Sprints, New Backlog (Amit)

#298 [skip ci] - fix bump_version.sh when latest RC and ga versions are the same
  .buildkite/pipeline_scripts/bump_version.sh
  .buildkite/pipeline_scripts_tests/bump_version_test.bat
Labels: Sprints - Barzelim, Sprint 22 (28/1 - 10/2)

#299 CU-3bfn5zu - allow to patch hpa
  charts/komodor-agent/templates/clusterrole.yaml
Labels: Operate Sprints, New Backlog (Amit)

#301 fix(chart/komodor-agent): daemonset not starting when configuring proxy
  .buildkite/tests/values_capabilities_proxy_test.py
  .buildkite/vulnerability-scan/exclude.yaml
  charts/komodor-agent/templates/metrics/_containers.tpl
Labels: Main Backlog

#302 chore(CD): Publish helm chart to docker-hub
  .buildkite/pipeline.yml
  publish.sh
Labels: Sprints - Barzelim, Sprint 23 (11/2 - 24/2)

#304 CU-86bxgbqzf - Add requests and limits to node-enricher
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 23 (11/2/24 - 24/2/24)
