Repository komodorio/helm-charts, pull requests merged in 2024-01, with the labels that each got.

#289 [skip ci] Change RC version from +RC to -RC to support proper semVer
  .buildkite/pipeline.yml
  .buildkite/pipeline_scripts/bump_version.sh
  .buildkite/pipeline_scripts/update_agent.sh
  .buildkite/pipeline_scripts_tests/bump_version_test.bat
  .buildkite/validate_helm_chart_updated.py
Labels: Sprints - Barzelim, Sprint 19 (17/12 - 30/12)

#290 cfg: add mgmtServerHost communications configuration
  .buildkite/pipeline.yml
  .buildkite/pipeline_scripts/legacy_test_helm_new_install.sh
  .buildkite/pipeline_scripts/legacy_test_helm_update_install.sh
  .buildkite/pipeline_scripts/staging-values.yaml
  .buildkite/tests/values_capabilities_proxy_test.py
  .buildkite/tests/values_capabilities_test.py
  .buildkite/tests/values_components_test.py
  .gitignore
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, BACKLOG

#292 added restarts total to metrics collector inventory plugin
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
Labels: Operate Sprints, Sprint 16 (31/12 - 13/1)

#294 CU-86bx2d9ge - chore(ci): Add list of images to the release-note and fix pipeline generation
  .buildkite/pipeline_scripts/create_gh_draft_release.sh
  .buildkite/release_checks/pipeline/generate.py
Labels: Sprints - Barzelim, Sprint 21 (14/1 - 27/1)

#295 CU-86bx2kutq - fix: Allow multiline values, fix resources mapping for supervisor container
  .buildkite/tests/values_capabilities_test.py
  charts/komodor-agent/templates/configmap.yaml
  charts/komodor-agent/templates/watcher/_containers.tpl
Labels: Sprints - Barzelim, Sprint 21 (14/1 - 27/1)
