Repository komodorio/helm-charts, pull requests merged in 2025-05, with the labels that each got.

#367 CU-86c35jn0c: Update with the recent agent routes changes
  .buildkite/pipeline_scripts/staging-values.yaml
  scripts/helm-migration/mapping.go
Labels: Operate Sprints, Sprint 51 (4/5 - 17/5)

#368 CU-86c38wcge - bump version
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 55 (4/5/25 - 18/5/25)

#366 CU-86c3chx0b Add flag to use new GPU metrics collecting
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/metrics/_containers_deamon.tpl
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
  charts/komodor-agent/values.yaml
Labels: hidden, GPU

#371 CU-86c3k36gc - Add Klaudia CRD to agent chart
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/clusterrole.yaml
  charts/komodor-agent/templates/crd/klaudia.yaml
  charts/komodor-agent/values.yaml
Labels: hidden, CTO

#373 CU-86c3m8rev - Change default of DCGM to true
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 56 (18/5 - 31/5)

#374 CU-86c3majxz - Use newer DCGM detect version
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 56 (18/5 - 31/5)

#378 CU-86c3rx3zc - chore: disable installation in staging and production
  .buildkite/pipeline_scripts/production-values.yaml
  .buildkite/pipeline_scripts/staging-values.yaml
  charts/komodor-agent/templates/crd/klaudia.yaml
Labels: Sprints - Barzelim, Sprint 56 (18/5 - 31/5)

#379 CU-86c3runey - GPU diagnostics access container
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/metrics/_containers_daemon.tpl
  charts/komodor-agent/templates/metrics/_security.tpl
  charts/komodor-agent/templates/metrics/_volumes.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 56 (18/5 - 31/5)
