Repository komodorio/helm-charts, pull requests merged in 2025-06, with the labels that each got.

#381 feat: add new admission-controller component to komodor-agent chart
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/admission-controller/_helpers.tpl
  charts/komodor-agent/templates/admission-controller/configmap.yaml
  charts/komodor-agent/templates/admission-controller/deployment.yaml
  charts/komodor-agent/templates/admission-controller/service.yaml
  charts/komodor-agent/templates/admission-controller/webhookconfiguration.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 56 (18/5 - 31/5)

#383 add required cluster role permissions for admission controller if enabled
  charts/komodor-agent/templates/clusterrole.yaml
Labels: Sprints - Barzelim, Sprint 57 (1/6 - 14/6)

#384 CU-86c3wgdvd - Update version of admission controller and telegraf plugins
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 57 (1/6 - 14/6)

#386 add missing deployment annotations, add config checksum for auto-reloading, update admission-controller to latest release
  charts/komodor-agent/templates/admission-controller/deployment.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 57 (1/6 - 14/6)

#382 CU-86c3fkxbt - Use remote config for telegraf
  .buildkite/tests/helpers/kubernetes_helper.py
  .buildkite/tests/values_capabilities_proxy_test.py
  .buildkite/tests/values_components_test.py
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/_custom_ca.tpl
  charts/komodor-agent/templates/_proxy_conf.tpl
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/templates/metrics/_containers_daemon.tpl
  charts/komodor-agent/templates/metrics/_containers_deployment.tpl
  charts/komodor-agent/templates/metrics/_helpers.tpl
  charts/komodor-agent/templates/metrics/_volumes.tpl
  charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 57 (1/6/25 - 15/6/25)

#388 Add priority class for admission-controller, update telegraf plugin to build3 to include the 'mutated' tag to metrics, update admission-controller to 0.0.11 for scheduling priority support
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/admission-controller/_helpers.tpl
  charts/komodor-agent/templates/admission-controller/deployment.yaml
  charts/komodor-agent/templates/priorityclasses.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 57 (1/6 - 14/6)

#391 separate the admission controller cluster role and service account to its own resources
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/admission-controller/_service_account.tpl
  charts/komodor-agent/templates/admission-controller/deployment.yaml
  charts/komodor-agent/templates/admission-controller/rbac.yaml
  charts/komodor-agent/templates/admission-controller/serviceaccount.yaml
  charts/komodor-agent/templates/clusterrole.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 57 (1/6 - 14/6)

#390 CU-86c3y86mt - Add missing env var
  charts/komodor-agent/templates/metrics/_containers_daemon.tpl
Labels: Sprints - Troubleshooting, Sprint 57 (1/6/25 - 15/6/25)

#396 CU-86c3zhzd0 - Update telegraf image versions to v1.34.4-build4 for both Alpine and …
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 57 (1/6/25 - 15/6/25)

#395 CU-86c3zc0kd - Add command for metrics container in daemonset template
  charts/komodor-agent/templates/metrics/_containers_daemon.tpl
Labels: Sprints - Troubleshooting, Sprint 57 (1/6/25 - 15/6/25), Sprint 58 (15/6/25 - 29/6/25)

#398 CU-86c40bu76 - Separate gpu accessor daemonset
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/_helpers.tpl
  charts/komodor-agent/templates/crd/klaudia.yaml
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_gpu.yaml
  charts/komodor-agent/templates/metrics/_containers_daemon.tpl
  charts/komodor-agent/templates/metrics/_volumes.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 57 (1/6 - 14/6)

#403 Add sidecar config container to metrics daemon and deployment
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/templates/deployment_metrics.yaml
  charts/komodor-agent/templates/metrics/_containers_daemon.tpl
  charts/komodor-agent/templates/metrics/_containers_deployment.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 58 (15/6/25 - 29/6/25)
