Repository komodorio/helm-charts, pull requests merged in 2025-09, with the labels that each got.

#424 Admission controller - rework values and configs, update to 0.1.11
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/admission-controller/configmap.yaml
  charts/komodor-agent/templates/admission-controller/deployment.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 63 (24/8 - 7/9)

#428 CU-86c5bhpca - add description to klaudia crd
  charts/komodor-agent/templates/_helpers.tpl
  charts/komodor-agent/templates/crd/klaudia.yaml
Labels: Main Backlog

#430 CU-86c5h62kf - update binpacking configuration to true by default
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 64 (7/9 - 21/9)

#432 add memory checker utility to check recommended memory requirements
  charts/komodor-agent/README.md
  charts/komodor-agent/README.md.gotmpl
  charts/komodor-agent/utilities/memory-planning/01-namespace.yaml
  charts/komodor-agent/utilities/memory-planning/02-configmap.yaml
  charts/komodor-agent/utilities/memory-planning/03-serviceaccount.yaml
  charts/komodor-agent/utilities/memory-planning/04-clusterrole.yaml
  charts/komodor-agent/utilities/memory-planning/05-clusterrolebinding.yaml
  charts/komodor-agent/utilities/memory-planning/06-job.yaml
  charts/komodor-agent/utilities/memory-planning/README.md
Labels: Sprints - Barzelim, Sprint 65 (21/9 - 5/10)

#436 CU-86c5qqtem - Fix `helm-docs` installation: add missing `sudo`
  charts/komodor-agent/Makefile
Labels: Operate Sprints, Sprint 61 (21/9 - 5/10)

#435 Support Spark in rightsizing webhook: reinvocation policy + RBAC
  charts/komodor-agent/templates/admission-controller/rbac.yaml
  charts/komodor-agent/templates/admission-controller/webhookconfiguration.yaml
  charts/komodor-agent/values.yaml
Labels: Operate Sprints, Sprint 61 (21/9 - 5/10)

#438 Update Admission Controller
  charts/komodor-agent/values.yaml
Labels: Operate Sprints, Sprint 61 (21/9 - 5/10)
