Repository komodorio/helm-charts, pull requests merged in 2025-07, with the labels that each got.

#408 CU-86c4byh2t - Deploy OTEL Collector by default for internal telemetry
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/configmap.yaml
  charts/komodor-agent/templates/opentelemetry/_containers.tpl
  charts/komodor-agent/templates/opentelemetry/_helpers.tpl
  charts/komodor-agent/templates/opentelemetry/configmap.yaml
  charts/komodor-agent/templates/opentelemetry/service.yaml
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 59 (29/6 - 13/7)

#410 [skip-ci] fix cu-86c4jzxbv
  charts/komodor-agent/templates/NOTES.txt
Labels: Main Backlog

#411 add a checksum to automatically refresh controller server with new certificates and configuration if they change
  charts/komodor-agent/templates/admission-controller/deployment.yaml
Labels: Sprints - Barzelim, Sprint 60 (13/7 - 27/7)

#413 CU-86c4rynbw - update telegraf to v2.0.3 which upgrades admission-controller package its using
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 61 (27/7 - 10/8)
