Repository komodorio/helm-charts, pull requests merged in 2025-02, with the labels that each got.

#348 deprecate: network-mapper
  .buildkite/tests/values_capabilities_test.py
  charts/komodor-agent/Makefile
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/configmap.yaml
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/deployment.yaml
  charts/komodor-agent/templates/network-mapper/_containers.tpl
  charts/komodor-agent/templates/network-mapper/_helpers.tpl
  charts/komodor-agent/templates/network-mapper/_network.tpl
  charts/komodor-agent/templates/network-mapper/_volumes.tpl
  charts/komodor-agent/templates/network-mapper/cluster-role.yaml
  charts/komodor-agent/templates/network-mapper/configmap.yaml
  charts/komodor-agent/templates/network-mapper/role.yaml
  charts/komodor-agent/templates/network-mapper/roles-binding.yaml
  charts/komodor-agent/templates/network-mapper/service.yaml
  charts/komodor-agent/templates/watcher/_security.tpl
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 48 (26/1 - 8/2)

#349 [skip ci] security: scan images using WIZ cli
  .buildkite/vulnerability-scan/exclude.yaml
  .buildkite/vulnerability-scan/main.py
  .buildkite/vulnerability-scan/pipeline.yaml
  .buildkite/vulnerability-scan/requirements.txt
  .buildkite/vulnerability-scan/scan_image_with_wiz.sh
  .buildkite/vulnerability-scan/tests.py
Labels: Sprints - Barzelim, Sprint 48 (26/1 - 8/2)

#350 CU-86c1x2ce7 - chore: update to version 1.33.1
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 48 (26/1 - 8/2)

#351 fixing hpa permissions to be included under capabilities.actions
  charts/komodor-agent/templates/clusterrole.yaml
Labels: Sprints - Barzelim, Sprint 49 (9/2 - 22/2)

#353 Cu-86c1xeb56 chore: update telegraf image version to v1.33.2-alpine
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 49 (9/2/25 - 23/2/25)

#354 Support host network
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/values.yaml
Labels: Main Backlog
