Repository komodorio/helm-charts, pull requests merged in 2025-03, with the labels that each got.

#352 CU-86c1z5mux - add basicstats aggregator and regex processor to metrics confingmaps
  charts/komodor-agent/templates/metrics/configmap-daemon-windows.yaml
  charts/komodor-agent/templates/metrics/configmap-daemon.yaml
Labels: Sprints - Troubleshooting, Sprint 49 (9/2/25 - 23/2/25)

#357 CU-86c289u54 - update Telegraf image versions to v1.33.3-2
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Troubleshooting, Sprint 50 (23/2/25 - 9/3/25)

#358 CU-86c29wdvt fix duplicate command
  charts/komodor-agent/templates/daemonset.yaml
  charts/komodor-agent/templates/deployment_metrics.yaml
  charts/komodor-agent/templates/metrics/_containers_deamon.tpl
  charts/komodor-agent/templates/metrics/_containers_deployment.tpl
Labels: Main Backlog

#360 CU-86c2f0mpdstop - serviceaccount template from generating when imagePullSecret is specified
  charts/komodor-agent/templates/serviceaccount.yaml
Labels: Main Backlog

#362 feat: add rbac-cluster-sync params
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 51 (9/3 - 23/3)

#363 fix: remove hostNetwork parameter from komodorDaemonWindows configuration - not supported on windows
  charts/komodor-agent/README.md
  charts/komodor-agent/templates/daemonset_windows.yaml
  charts/komodor-agent/values.yaml
Labels: Main Backlog

#364 security: bump versions
  charts/komodor-agent/README.md
  charts/komodor-agent/values.yaml
Labels: Sprints - Barzelim, Sprint 52 (23/3 - 6/4)
